name: Testing

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
  schedule:
    - cron: 0 * * * *

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bundle
        run: bundle install
      - name: Dependencies
        run: pod install
      - name: Run swiftlint
        run: bundle exec fastlane lint

  test:
    needs: lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bundle
        run: bundle install
      - name: Dependencies
        run: pod install
      - name: Test
        run: bundle exec fastlane tests
        continue-on-error: true
      - name: Upload test results with default CLI version
        uses: trunk-io/analytics-uploader@main
        with:
          org-slug: gabes-org-2
          token: ${{ secrets.TRUNK_PROD_ORG_API_TOKEN }}
          xcresult-path: fastlane/test_output/UpcomingMovies.xcresult
          quarantine: true
        env:
          TRUNK_PUBLIC_API_ADDRESS: https://api.trunk.io
        continue-on-error: true
      - name: Upload test results with default CLI version
        uses: trunk-io/analytics-uploader@main
        with:
          org-slug: simple-test-org-2
          token: ${{ secrets.TRUNK_PROD_ORG_API_TOKEN_SIMPLE }}
          xcresult-path: fastlane/test_output/UpcomingMovies.xcresult
          quarantine: true
        env:
          TRUNK_PUBLIC_API_ADDRESS: https://api.trunk.io
