name: Testing

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]
  schedule:
    - cron: 0 * * * *

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bundle
        run: bundle install
      - name: Dependencies
        run: pod install
      - name: Run swiftlint
        run: bundle exec fastlane lint


  test:
    needs: lint
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bundle
        run: bundle install
      - name: Dependencies
        run: pod install
      - name: Setup Xcode 15
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15
      - name: Test
        run: bundle exec fastlane tests
        continue-on-error: true
      - uses: actions/upload-artifact@v4
        with:
          name: cross-gem-${{ matrix.platform }}
          path: fastlane/test_output/UpcomingMovies.xcresult
          if-no-files-found: error
          retention-days: 1
      - name: Check xcresulttool version
        continue-on-error: true
        run: xcrun xcresulttool --version
      - name: Run xcresulttool
        run: xcrun xcresulttool get object --format json --path fastlane/test_output/UpcomingMovies.xcresult
        continue-on-error: true
      - name: Upload test results with default CLI version
        uses: trunk-io/analytics-uploader@main
        with:
          org-slug: gabes-org-2
          token: ${{ secrets.TRUNK_PROD_ORG_API_TOKEN }}
          xcresult-path: fastlane/test_output/UpcomingMovies.xcresult
          quarantine: true
	  cli-version: 0.7.0-beta.1
        env:
          TRUNK_PUBLIC_API_ADDRESS: https://api.trunk.io
        
